Attribute VB_Name = "shtIN"
Attribute VB_Base = "0{00020820-0000-0000-C000-000000000046}"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Attribute VB_TemplateDerived = False
Attribute VB_Customizable = True
Attribute VB_Control = "txtestoque, 7, 2, MSForms, TextBox"
Attribute VB_Control = "txtlin, 6, 3, MSForms, TextBox"
Attribute VB_Control = "SpinButton1, 5, 4, MSForms, SpinButton"
Attribute VB_Control = "txtgrupo, 3, 5, MSForms, TextBox"
Attribute VB_Control = "txtdesc, 2, 6, MSForms, TextBox"
Attribute VB_Control = "txtcod, 1, 7, MSForms, TextBox"
Attribute VB_Control = "txtcategoria, 9, 8, MSForms, TextBox"
Attribute VB_Control = "txtqtd, 10, 9, MSForms, TextBox"
Option Explicit

